---
- name: install packages for docker
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - device-mapper-persistent-data
    - lvm2
  
- name: download repository file
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker
  yum:
    name: "docker-ce-{{ docker_version }}"

- name: create kubernetes repository file
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: install kubectl
  yum:
    name: kubectl

- name: start docker
  systemd: 
    name: docker
    state: started
    enabled: yes

- name: download minikube
  get_url:
    url: "https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64"
    dest: /usr/local/bin/minikube
    mode: 0755
